/* LET US IDENTIFY WHERE THE ELEMENTS WE NEED TO PUT CONTENT */ 
/* JAVASCRIPT USES THE DOM TO FIGURE OUT WHERE TO COMMUNICATE WITH HTML*/ 
/* HTML COMMUNICATES BACK USING CLASSES/IDS/ATTRIBUTES AS IDENTIFIERS FOR JAVASCRIPT TO MANIPULATE OR CHANGE*/ 
/* JAVASCRIPT INTERPRETS ELEMENTS AS OBJECTS WITH PROPERTIES AND VALUES*/ 
/* WE USE JAVASCRIPT OBJECT SYNTAX TO WORK WITH HTML*/ 


